language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
before_install:
  - curl -OL https://github.com/google/protobuf/releases/download/v3.7.1/protoc-3.7.1-linux-x86_64.zip
  - sudo unzip -o protoc-3.7.1-linux-x86_64.zip -d /usr/local bin/protoc
  - sudo unzip -o protoc-3.7.1-linux-x86_64.zip -d /usr/local include/*
script:
    - PATH=$HOME/bin:$PATH cargo build
